# other parameters are ignored
frequency: 100
two_d_mode: false

map_frame: world
odom_frame: origin
base_link_frame: car
world_frame: world

odom0: odometry/filtered_wheel
odom0_config: [false, false, false,false, false, false,true,  true,  false,false, false, true,false, false, false]
odom0_queue_size: 100

pose0: car_pose
pose0_config: [true, true,   true,true,  true,  true,false, false, false,false, false, false,false, false, false]
pose0_queue_size: 100
pose0_nodelay: true